import { AppBar, CssBaseline, makeStyles } from '@mui/material';
import Head from 'next/head';
import Image from 'next/image';
import { Layout } from '../src/components/Layout';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CssBaseline />
        <Layout />
      </main>
    </>
  );
}
